"""File with constants for different magic numbers
"""

ENTER_ORD_CODE = 10
ESCAPE_ORD_CODE = 27
BACKSPACE_ORD_CODE_1 = 8
BACKSPACE_ORD_CODE_2 = 127

CURSES_BOX_LINES = 18
CURSES_BOX_COLS = 78
CURSES_BOX_BEGIN_Y = 2
CURSES_BOX_BEGIN_X = 2

WORDS_PATH = "/../data/english_top_1000.txt"
DEFAULT_SINGLE_PLAYER_WORDS = int(10)
